name: Fabric bug report
description: Create a report to help us improve the Fabric version
title: "[BUG] "
labels: ["modloader: Fabric", "type: 🐛 bug"]
assignees:
  - RakSrinaNa
body:
  - type: textarea
    id: describing
    attributes:
      label: Describe the bug
      description: Describe what happens and what you expected instead
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft version
      placeholder: 1.16.5
    validations:
      required: true
  - type: input
    id: fabric-version
    attributes:
      label: Fabric API version
      placeholder: 0.36.0
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod version
      placeholder: 2.10.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
