name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: RakambdaOrg/rakambda-github-workflows/.github/workflows/gradle-minecraft-build.yml@main
    with:
      java-version: ${{ vars.JAVA_VERSION }}
      game-tests: ${{ github.event_name == 'pull_request' }}
      game-tests-report-path: |
        fabric/build/gametest/junit.xml
        fabric/build/run/gameTest/logs/
        forge/run/test/logs/
        neoforge/run/test/logs/
